sudo: false

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

matrix:
  # Ignore failures for unstable versions
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements.txt

before_script:
  - flake8 --exclude __init__.py markdown_generator

script:
  - nosetest
